#! /bin/bash
#set -x
# this is a laziest of scripts with wayyyyyy to many dependancies built in for a <20 liner, but it works for me
BIN=/home/sshilton/bin/
"$BIN"/chknag
out=$?
if [ $out -eq 0 ];
	then
	sudo service nagios restart 
	echo "nagios service restarted"
else
	echo "nagios service config files are not syntacticly correct"
	echo "run chknag or if not available, run nagios -v $NAGIOS_HOME$/etc/nagios.cfg"
fi
